## Tutorial 5
### NumPy

NumPy is a fundamental package for scientific computing in Python.

<url>https://numpy.org/</url>

To install NumPy in Jupyter Notebook using pip, run the following cell:

In [ ]:
!pip install numpy 

Import the NumPy package

In [ ]:
import numpy as np

### Arrays
- Standard Python Library array only handles one-dimensional arrays and offers less functionality.
- NumPy’s array class is called ndarray. 
- It provides a powerful N-dimensional array object. 
- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers.
- In NumPy dimensions are called axes.

In [ ]:
a = np.array([1, 2, 3]) # Create an array with 1 axes and a length of 3
print (a)
print (type(a)) # Return the type of the object, a

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
print (a.ndim) # Return the number of axes (dimensions) of the array
print (a.shape) # Return the dimensions of the array
print (a.size) # Return the number of elements
print (a.dtype.name) # Return the type of the elements in the array

1
(3,)
3
int32


In [ ]:
b = np.array([[ 1., 0., 0.], 
              [ 0., 1., 2.]]) # Create an array with 2 axes
                              # 1st axis has a length of 2, 
                              # 2nd axis has a length of 3 
print (b)
print (type(b))

[[1. 0. 0.]
 [0. 1. 2.]]
<class 'numpy.ndarray'>


In [ ]:
print (b.ndim)
print (b.shape)
print (b.size)
print (b.dtype.name)

2
(2, 3)
6
float64


NumPy offers several functions to create arrays with initial placeholder content.

In [ ]:
np.zeros( (3, 4) ) # Create an array full of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones( (3, 4) ) # Create an array full of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full( (3, 4), 5) # Create a constant array

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
np.arange(10) # Return an array with a sequence of numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 10, 2) # Return an array with a sequence of numbers

array([1, 3, 5, 7, 9])

In [ ]:
print (np.linspace(0, 9, 3)) # Return an array with 3 evenly spaced numbers
                             # between 0 to 9

[0.  4.5 9. ]


Change the shape of the array

In [ ]:
a = np.array([ [0, 1, 2, 3], [4, 5, 6, 7]])
print ("a =", a)
b = a.reshape(4, 2)
print ("b =", b)
a.resize(4, 2)
print ("a =", a)
c = a.ravel()
print ("c =", c)

a = [[0 1 2 3]
 [4 5 6 7]]
b = [[0 1]
 [2 3]
 [4 5]
 [6 7]]
a = [[0 1]
 [2 3]
 [4 5]
 [6 7]]
c = [0 1 2 3 4 5 6 7]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners.

In [ ]:
print (np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [ ]:
print (np.arange(10000).reshape(500, 20)) # reshape() returns an array 
                                          # with a modified shape

[[   0    1    2 ...   17   18   19]
 [  20   21   22 ...   37   38   39]
 [  40   41   42 ...   57   58   59]
 ...
 [9940 9941 9942 ... 9957 9958 9959]
 [9960 9961 9962 ... 9977 9978 9979]
 [9980 9981 9982 ... 9997 9998 9999]]


Transposing the array

In [ ]:
a = np.array([ [0, 1, 2, 3], [4, 5, 6, 7]]) # 2 x 4 array
print ("a =", a)
print ("shape = ", a.shape)

b1 = a.transpose() # standard transpose of the 2D array
print ("b1 =", b1)

b2 = a.transpose(1, 0) # transpose of the 2D array with permutation of axes [1, 0]
                       # i.e. from (2, 4) to (4, 2)
print ("b1 =", b1)

b2 = a.transpose(1, 0) # transpose of the 2D array with permutation of axes [0, 1]
                       # i.e. from (2, 4) to (2, 4)
print ("b1 =", b1)

c = a.reshape(4, 2) # reshape the array c to a 2D array with 4 rows and 2 cols
print ("c =", c)


a = [[0 1 2 3]
 [4 5 6 7]]
shape =  (2, 4)
b1 = [[0 4]
 [1 5]
 [2 6]
 [3 7]]
b1 = [[0 4]
 [1 5]
 [2 6]
 [3 7]]
b1 = [[0 4]
 [1 5]
 [2 6]
 [3 7]]
c = [[0 1]
 [2 3]
 [4 5]
 [6 7]]


Flip the array - reverse the elements in the array with the shape unchanged.

In [28]:
a = np.array([ [0, 1, 2, 3], [4, 5, 6, 7]]) # 2 x 4 array
print ("a =", a)
print ("shape = ", a.shape)

b = np.flip(a)
print ("b = ", b)
print ("shape = ", b.shape)

a = [[0 1 2 3]
 [4 5 6 7]]
shape =  (2, 4)
b =  [[7 6 5 4]
 [3 2 1 0]]
shape =  (2, 4)


Reshape vs Transpose vs Flip

In [27]:
a = np.arange(12).reshape(3, 4) # numpy.ndarray.reshape() equivalent to numpy.reshape()
print ("a =", a)
print ("shape = ", a.shape)

b = a.reshape(4, 3)
print ("b =", b)

c = a.transpose() # numpy.ndarray.transpose() equivalent to numpy.transpose()
print ("c =", c)

d = np.flip(a) # numpy.flip()
print ("d = ", d)


a = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape =  (3, 4)
b = [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
c = [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
d =  [[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


Arithmetic operators on arrays apply elementwise. 

In [ ]:
a = np.arange(0, 12).reshape(3, 4)
print (a)
print (a * 10)
print (a < 10)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]]


Matrix product

In [ ]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[1, 2], [3, 4]])

print (a * b) # Return elementwise product
print (a @ b) # Return matrix product
print (a.dot(b)) # Return matrix product

[[1 0]
 [0 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


Indexing and Slicing

In [ ]:
# Indexing and slicing on one-dimensional array
a = np.arange(0, 8, 2)
print (a)
print (a[2]) # Indexing
print (a[1:3]) # Slicing

[0 2 4 6]
4
[2 4]


In [ ]:
# Indexing and slicing on multi-dimensional array
b = np.arange(0, 24, 2).reshape(3, 4)
print (b)
print (b[1, 2])  # Indices are given in a tuple separated by commas
print (b[0:2, 1]) # Slicing returns each row in the second column
print (b[:, 1]) # Slicing returns each row in the second column

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
12
[ 2 10]
[ 2 10 18]


Iterating

In [ ]:
b = np.arange(0, 24, 2).reshape(3, 4)
for row in b:
    print (row)

[0 2 4 6]
[ 8 10 12 14]
[16 18 20 22]


In [ ]:
for x in b.flat:
    print (x)

0
2
4
6
8
10
12
14
16
18
20
22


Copying

In [ ]:
a = np.arange(6).reshape(2, 3) # [[0,1,2],[3,4,5]]
print (a)

b = a # b is a reference of a, not a new array object
b[0, 2] = 100 # Modifying one of b's elements
print (a) # a is modified 

[[0 1 2]
 [3 4 5]]
[[  0   1 100]
 [  3   4   5]]


In [ ]:
a = np.arange(6).reshape(2, 3) # [[0,1,2],[3,4,5]]
b = a.copy() # b is a new array object

b[0, 2] = 100 # Modifying one of b's elements
print (a) # Only b is modified, but not a

[[0 1 2]
 [3 4 5]]


In [ ]:
a = np.arange(6).reshape(2, 3) # [[0,1,2],[3,4,5]]
b = a.view() # b is a new array object

b[0, 2] = 100 # Modifying one of b's elements
b.resize(3, 2) # b's shape is changed
print (a) # a's data is changed but shape is not changed

[[  0   1 100]
 [  3   4   5]]


In [ ]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
b = a[:2] # b is a new array object: [[0,1,2],[3,4,5]]
b[0, 2] = 100 # Modifying one of b's elements
print (a) # a is also modified

[[0 1 2]
 [3 4 5]]
[[  0   1 100]
 [  3   4   5]
 [  6   7   8]]


Indexing with Boolean Array

In [ ]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
print (a>0)

[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
print (a[ a<5 ])
print (a[ a%2 == 0 ])

[0 1 2 3 4]
[0 2 4 6 8]


Indexing with Array of Indices

In [ ]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
i = np.array([[0,2], [0, 1]])
print (a[i])

[[[0 1 2]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]]]


### Data Types

In [ ]:
x = np.double(1)
print (x)

1.0


In [ ]:
y = np.intc([0.5, 1.5, 2.5])
print (y)

[0 1 2]


In [ ]:
z = np.arange(5, dtype=np.double)
print (z)

[0. 1. 2. 3. 4.]


In [ ]:
w = np.array([0.5, 1.5, 2.5], dtype=np.single)
print (w)

[0.5 1.5 2.5]


In [ ]:
a = w.astype(int) # Return a copy of the array casted to the given type
print (a)

[0 1 2]
