In [1]:
import torch

In [ ]:
net1 = torch.nn.Sequential(
    torch.nn.Conv2d(1, 1, 3, stride=2, padding=1, dilation=1),
    torch.nn.ReLU(),
    torch.nn.Conv2d(1, 1, 3, stride=1, padding=1, dilation=1),
)
net2 = torch.nn.Sequential(
    torch.nn.Conv2d(1, 1, 3, stride=1, padding=1, dilation=1),
    torch.nn.ReLU(),
    torch.nn.Conv2d(1, 1, 3, stride=1, padding=2, dilation=2),
)
for p1, p2 in zip(net1.parameters(), net2.parameters()):
    p2.data = p1.data.clone()
    p2.requires_grad = True

print(list(net1.parameters()))
print(list(net2.parameters()))

x = torch.randn(1, 1, 32, 32)
print(x.shape, net1(x).shape)
print(x.shape, net2(x).shape)
y1 = net1(x)
y2 = net2(x)
print(y1)
print(y2[:, :, ::2, ::2])

[Parameter containing:
tensor([[[[ 0.2899,  0.0979, -0.2296],
          [-0.2907, -0.1464, -0.1634],
          [-0.2028, -0.3216,  0.2284]]]], requires_grad=True), Parameter containing:
tensor([0.0907], requires_grad=True), Parameter containing:
tensor([[[[ 0.0457, -0.0583, -0.2322],
          [-0.0520, -0.1056, -0.0569],
          [-0.1764, -0.2853, -0.1077]]]], requires_grad=True), Parameter containing:
tensor([0.2327], requires_grad=True)]
[Parameter containing:
tensor([[[[ 0.0278, -0.2255, -0.2025],
          [-0.2487,  0.1943,  0.0574],
          [ 0.0170, -0.2974, -0.1704]]]], requires_grad=True), Parameter containing:
tensor([0.1391], requires_grad=True), Parameter containing:
tensor([[[[ 0.2028,  0.1040, -0.2306],
          [-0.2404, -0.1529,  0.1846],
          [-0.2681,  0.3321, -0.2321]]]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
torch.Size([1, 1, 32, 32]) torch.Size([1, 1, 16, 16])
torch.Size([1, 1, 32, 32]) torch.Size([1, 1, 32, 32]

In [ ]:
net1 = torch.nn.Sequential(
    torch.nn.Conv2d(1, 1, 3, stride=2, padding=1, dilation=1),
    torch.nn.ReLU(),
    torch.nn.Conv2d(1, 1, 3, stride=1, padding=1, dilation=1),
    torch.nn.ReLU(),
    torch.nn.ConvTranspose2d(1, 1, 3, stride=2, padding=1, output_padding = 1), #add padding for consistent shape
)
x = torch.randn(1, 1, 5, 5)
print(net1(x)[:, :, :x.shape[2], :x.shape[3]].shape) #cut to produce same input shape as output shape

torch.Size([1, 1, 5, 5])
